[package]
name = "trader"
version = "0.1.0"
authors = ["RollenRegistratorBot <rollenseb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpaca = {version = "0.1", path = "../alpaca"}
anyhow = "1.0"
futures = "0.3"
rdkafka = "0.23"
serde = "1.0.113"
tokio = {version = "0.2", features = ["macros", "rt-threaded"]}
uuid = "0.8"
serde_json = "1.0.55"
clap = "2.33.1"
