[package]
name = "trader"
version = "0.1.0"
authors = ["RollenRegistratorBot <rollenseb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpaca = {version = "0.2", git = "https://github.com/AiaiaCapital/alpaca"}
anyhow = "1.0.32"
futures = "0.3.5"
rdkafka = {version = "0.24.0", features = ["ssl-vendored"]}
serde = "1.0.116"
tokio = { version = "0.2.22", features = ["macros", "rt-threaded"] }
uuid = "0.8.1"
serde_json = "1.0.57"
clap = "2.33.3"
log = "0.4.11"
env_logger = "0.7.1"
thiserror = "1.0.20"
dotenv = "0.15.0"
