[package]
name = "trader"
version = "0.1.0"
authors = ["RollenRegistratorBot <rollenseb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpaca = {version = "0.2", git = "https://github.com/AiaiaCapital/alpaca"}
anyhow = "1.0.32"
clap = "2.33.3"
dotenv = "0.15.0"
futures = "0.3.5"
rdkafka = {version = "0.24.0", features = ["ssl-vendored"]}
serde = "1.0.116"
serde_json = "1.0.57"
thiserror = "1.0.20"
tokio = { version = "0.2.22", features = ["macros", "rt-threaded"] }
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = "0.2"
tracing-bunyan-formatter = "0.1"
uuid = "0.8.1"
