apiVersion: v1
kind: ConfigMap
metadata:
  name: trader
data:
  bootstrap_servers: "pkc-ep9mm.us-east-2.aws.confluent.cloud:9092"
  apca_api_base_url: "https://paper-api.alpaca.markets/v2"
  group_id: "trader"
  order_intent_topic: "intended-trades"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader-deployment
spec:
  selector:
    matchLabels:
      app: trader
  replicas: 1
  template:
    metadata:
      labels:
        app: trader
    spec:
      containers:
      - name: trader
        image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/trader:${IMAGE_TAG}
        env:
        - name: APCA_API_KEY_ID
          valueFrom:
            secretKeyRef:
              name: alpaca
              key: APCA_API_KEY_ID
        - name: APCA_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: alpaca
              key: APCA_API_SECRET_KEY
        - name: SASL_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka
              key: SASL_USERNAME
        - name: SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka
              key: SASL_PASSWORD
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: trader
              key: bootstrap_servers
        - name: APCA_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: trader
              key: apca_api_base_url
        - name: GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: trader
              key: group_id
        - name: ORDER_INTENT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: trader
              key: order_intent_topic
